---
- name: include all tasks    
  block:
   - include_tasks: "createDirectory.yml"
   - include_tasks: "downloadNexusPackage.yml"
   - include_tasks: "untarNexusPackage.yml"  
   - include_tasks: "changeOwnership.yml"
   - include_tasks: "injectconfiguration.yml"
   - include_tasks: "removeNexusPackage.yml"
  become: true
  become_user: root
- name: command running
  command: nohup /data/nexus/3.13.0-01/nexus-3.13.0-01/bin/nexus run
  
